[package]
name = "heligen"
version = "0.1.0"
authors = ["VoxWave <victor_bankowski@hotmail.com>"]
edition = "2018"

[dependencies]
cpal = "0.9.0"
hound = "3.4.0"
rand = "0.7.2"
wasmtime = "0.23.0"
crossbeam = "0.8.0"

