[package]
name = "test_module"
version = "0.1.0"
authors = ["Victor Bankowski <victor_bankowski@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
